apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  interval: 1m
  url: "https://github.com/Maria-1020/projet_nextcloud"
  ref:
    branch: main
