redis:
  enabled: true
  master:
    persistence:
      enabled: false
  replica:
    persistence:
      enabled: false

externalDatabase:
  enabled: false

internalDatabase:
  enabled: true
  type: nextcloud
